int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int s_root(int n, int r);
int _sqrt_recursion(int n);
int is_divisible(int n, int d);
int is_prime_number(int n);
